import { chromium } from "playwright";
const [rota, arquivo, largura = "1440", altura = "900", tema = "light"] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: +largura, height: +altura }, colorScheme: tema });
const p = await ctx.newPage();
const erros = [];
p.on("console", (m) => m.type() === "error" && erros.push(m.text()));
p.on("pageerror", (e) => erros.push("pageerror: " + e.message));
await p.goto("http://localhost:3100" + rota, { waitUntil: "networkidle", timeout: 60000 });
await p.waitForTimeout(900);
const m = await p.evaluate(() => ({ sw: document.documentElement.scrollWidth, iw: window.innerWidth }));
await p.screenshot({ path: arquivo, fullPage: true });
if (m.sw > m.iw + 1) console.log(`ROLAGEM HORIZONTAL: ${m.sw} > ${m.iw}`);
for (const e of erros) console.log("ERRO:", e.slice(0, 300));
console.log("ok", arquivo);
await b.close();
